export const PUBLIC_ROUTES = {
	HOME: "/",
	ADMIN_LOGIN: "/back-office-login",
	VERIFY_OTP: "/verify-otp/:sessionId",
	FORGOT_PASSWORD: "/forgot-password",
	RESET_PASSWORD: "/reset-password",
	REGISTER_ORGANIZATION: "/register-organization",
	INVITE_ACCEPT: "/invite/accept",
	SIGNUP_REQUEST: "/signup-request",
};

export const COMMON_ROUTES = {
	ACCESS_RESTRICTED: "/access-restricted",
	FORBIDDEN: "/forbidden",
	CHANGE_PASSWORD: "/change-password",
	UPDATE_PROFILE: "/update-profile",
};
// Admin Routes
export const ADMIN_ROUTES = {
	DASHBOARD: "/admin",
	INVITE_ORGANIZATION: "/admin/invite",
	DOCUMENTS: "/admin/documents",
	ADD_DOCUMENT: "/admin/documents/add",
	EDIT_DOCUMENT: "/admin/documents/edit/:id",
	BENEFITS: "/admin/benefits",
	ADD_BENEFITS: "/admin/benefits/add",
	EDIT_BENEFITS: "/admin/benefits/edit/:id",
	ORGANIZATION_LISTING: "/admin/organizations",
	ORGANIZATION_REQUEST: "/admin/organization-request",
	INVITATION_LISTING: "/admin/invitation",
	EDIT_INVITATION: "/admin/invitation/:id",
	ORGANIZATION_DETAILS: "/admin/organizations/:id",
	USER_DIRECTORY: "/admin/users",
	ADD_USER: "/admin/users/add",
	EDIT_USER: "/admin/users/edit/:id",
	USER_DETAILS: "/admin/userdetails/:id",
	INVOICES: "/admin/invoices",
	INVOICE_DETAIL: "/admin/invoices/:id",
	PAYMENTS: "/admin/payments",
	PAYMENT_DETAILS: "/admin/payments/:cycleId",
	PAYROLL_DETAILS: "/admin/payroll-details",
	MAKE_PAYMENT: "/admin/make-payment",
	SETTINGS: "/admin/settings",
	CURRENCIES: "/admin/currencies",
	ADD_CURRENCY: "/admin/currencies/add",
	EDIT_CURRENCY: "/admin/currencies/edit/:id",
	GENERAL_INVOICES: "/admin/general-invoices",
	CREATE_GENERAL_INVOICE: "/admin/general-invoices/create",
	EDIT_GENERAL_INVOICE: "/admin/general-invoices/edit/:id",
	VIEW_GENERAL_INVOICE: "/admin/general-invoices/:id",
	CREATE_DOCUMENTS: "/admin/documents/create",
};

// Employee Routes
export const EMPLOYEE_ROUTES = {
	DASHBOARD: "/employee",
	LEAVES: "/employee/leaves",
	MYPAYMENTS: "/employee/mypayments",
	PAYDETAILS: "/employee/paydetails/:id",
	TIMESHEET: "/employee/timesheet",
	TIMESHEET_DETAIL: "/employee/timesheet/:id",
	UPDATE_INFO: "/employee/update-info",
	MY_CONTRACT: "/employee/contract",
};

// Organization Routes
export const ORG_ROUTES = {
	DASHBOARD: "/organization",
	HIRE: "/organization/hire",
	HIRE_EMPLOYEE: "/organization/hire-employee",
	INVITE_SUCCESS: "/organization/invite-success",
	TEAM: "/organization/team",
	WELCOME: "/organization/welcome",
	PAYROLL: "/organization/payroll",
	PAYROLL_DETAILS: "/organization/payrolldetails/:cycleId",
	PAYROLL_DETAILS_BASE: "/organization/payrolldetails",
	LEAVES: "/organization/leaves",
	MYPAYMENTS_ID: "/organization/mypayments/:id",
	PAYDETAILS: "/organization/paydetails",
	MAKE_PAYMENT: "/organization/make-payment",

	EMPLOYEE_LISTING: "/organization/employee",
	EMPLOYEE_DETAILS: "/organization/employee/:id",
	ADD_CONTRACT: "/organization/employee/:id/add-contract",
	EDIT_CONTRACT: "/organization/employee/:id/edit-contract",
	UPDATE_INFO: "/organization/update-info",
	DOCUMENTS: "/organization/documents",
	ADD_DOCUMENT: "/organization/documents/add",
	EDIT_DOCUMENT: "/organization/documents/edit/:id",
	TIMESHEET: "/organization/timesheet",
	TIMESHEET_DETAIL: "/organization/timesheet-detail/:id",
	INVOICE_ITEMS: "/organization/invoice-items",
	ADD_INVOICE_ITEM: "/organization/invoice-items/add",
	EDIT_INVOICE_ITEM: "/organization/invoice-items/edit/:id",
	INVOICES: "/organization/invoices",
	INVOICE_DETAIL: "/organization/invoices/:id",
	PROFILE: "/organization/profile",
	ADMINS: "/organization/admins",
	ADD_ADMIN: "/organization/admins/add",
	GENERAL_INVOICES: "/organization/general-invoices",
	VIEW_GENERAL_INVOICE: "/organization/general-invoices/:id",
};
